export type DietaryTag = "vegan" | "vegetarian" | "gluten-free" | "dairy-free" | "signature";

export interface MenuItem {
  id: number;
  category: string;
  name: string;
  price: string;
  description: string;
  image: string;
  tag: string | null;
  tagColor: string | null;
  dietary: DietaryTag[];
  allergens?: string;
}

export const menuItems: MenuItem[] = [
  // ── Coffee ──────────────────────────────────────────────────────────────────
  { id: 1,  category: "coffee",    name: "Rose Latte",            price: "320 ETB", description: "Velvety espresso with rose-infused steamed milk, topped with edible rose petals and gold dust", image: "https://images.unsplash.com/photo-1561882468-9110e03e0f78?w=400&q=80", tag: "Bestseller",     tagColor: "#D46A7E", dietary: ["vegetarian"],              allergens: "Milk" },
  { id: 2,  category: "coffee",    name: "Ethiopian Macchiato",   price: "150 ETB", description: "Traditional Ethiopian coffee ceremony style with a modern luxury presentation",                   image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&q=80", tag: "Local Favorite", tagColor: "#5C4033", dietary: ["vegan", "gluten-free"],    allergens: "None" },
  { id: 3,  category: "coffee",    name: "Café au Lait",          price: "220 ETB", description: "Classic French coffee with steamed whole milk, served in a traditional bowl",                     image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80", tag: null,             tagColor: null,      dietary: ["vegetarian"],              allergens: "Milk" },
  { id: 4,  category: "coffee",    name: "Cold Brew Royale",      price: "280 ETB", description: "18-hour cold-steeped Ethiopian Yirgacheffe, served over crystal ice with vanilla cream",          image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&q=80", tag: "New",            tagColor: "#D4A017", dietary: ["vegetarian"],              allergens: "Milk" },
  { id: 5,  category: "coffee",    name: "Espresso Classique",    price: "120 ETB", description: "Double shot of our signature house blend, extracted to perfection",                               image: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=400&q=80", tag: null,             tagColor: null,      dietary: ["vegan", "gluten-free"],    allergens: "None" },
  { id: 6,  category: "coffee",    name: "Caramel Macchiato",     price: "290 ETB", description: "Layered espresso with vanilla-infused milk and house-made caramel drizzle",                       image: "https://images.unsplash.com/photo-1485808191679-5f86510bd9d4?w=400&q=80", tag: null,             tagColor: null,      dietary: ["vegetarian"],              allergens: "Milk" },
  // ── Tea ─────────────────────────────────────────────────────────────────────
  { id: 7,  category: "tea",       name: "Rose Petal Chai",       price: "200 ETB", description: "Aromatic spiced chai infused with dried rose petals and cardamom",                                image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80", tag: "Signature",      tagColor: "#D46A7E", dietary: ["vegan", "gluten-free"],    allergens: "None" },
  { id: 8,  category: "tea",       name: "Moroccan Mint Tea",     price: "180 ETB", description: "Fresh spearmint leaves steeped in premium green tea, served ceremonially",                        image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&q=80", tag: null,             tagColor: null,      dietary: ["vegan", "gluten-free"],    allergens: "None" },
  { id: 9,  category: "tea",       name: "Earl Grey Supreme",     price: "190 ETB", description: "Premium bergamot-infused black tea with lavender and cornflower petals",                          image: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?w=400&q=80", tag: null,             tagColor: null,      dietary: ["vegan", "gluten-free"],    allergens: "None" },
  { id: 10, category: "tea",       name: "Chamomile Honey",       price: "170 ETB", description: "Soothing chamomile flowers with Ethiopian wild honey and a hint of lemon",                        image: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&q=80", tag: null,             tagColor: null,      dietary: ["vegan", "gluten-free"],    allergens: "None" },
  // ── Pastries ─────────────────────────────────────────────────────────────────
  { id: 11, category: "pastries",  name: "Croissant au Beurre",   price: "180 ETB", description: "Flaky, buttery French croissant baked fresh every morning with premium imported butter",          image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&q=80", tag: "Chef's Pick",    tagColor: "#D4A017", dietary: ["vegetarian"],              allergens: "Gluten, Milk, Eggs" },
  { id: 12, category: "pastries",  name: "Pain au Chocolat",      price: "200 ETB", description: "Buttery puff pastry filled with premium Belgian dark chocolate",                                  image: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=400&q=80", tag: null,             tagColor: null,      dietary: ["vegetarian"],              allergens: "Gluten, Milk, Eggs" },
  { id: 13, category: "pastries",  name: "Almond Croissant",      price: "220 ETB", description: "Classic croissant filled with rich almond cream and topped with toasted flaked almonds",          image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80", tag: null,             tagColor: null,      dietary: ["vegetarian"],              allergens: "Gluten, Milk, Eggs, Nuts" },
  { id: 14, category: "pastries",  name: "Cinnamon Danish",       price: "190 ETB", description: "Spiral pastry with cinnamon sugar filling, cream cheese glaze and toasted pecans",               image: "https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=400&q=80", tag: "New",            tagColor: "#D4A017", dietary: ["vegetarian"],              allergens: "Gluten, Milk, Eggs, Nuts" },
  // ── Breakfast ────────────────────────────────────────────────────────────────
  { id: 15, category: "breakfast", name: "Eggs Benedict Royale",  price: "480 ETB", description: "Poached eggs on toasted brioche with smoked salmon, hollandaise sauce and fresh herbs",           image: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=400&q=80", tag: "Bestseller",     tagColor: "#D46A7E", dietary: [],                          allergens: "Gluten, Milk, Eggs, Fish" },
  { id: 16, category: "breakfast", name: "French Toast Classique", price: "380 ETB", description: "Thick-cut brioche soaked in vanilla custard, pan-fried golden, served with maple syrup and berries", image: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=400&q=80", tag: null,          tagColor: null,      dietary: ["vegetarian"],              allergens: "Gluten, Milk, Eggs" },
  { id: 17, category: "breakfast", name: "Avocado Toast Luxe",    price: "350 ETB", description: "Sourdough toast with smashed avocado, poached egg, microgreens and truffle oil",                  image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=400&q=80", tag: "New",            tagColor: "#D4A017", dietary: ["vegetarian"],              allergens: "Gluten, Eggs" },
  { id: 18, category: "breakfast", name: "Full Parisian Breakfast", price: "550 ETB", description: "Croissant, fresh fruit, yogurt parfait, soft-boiled eggs, and your choice of coffee or tea",   image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=400&q=80", tag: "Chef's Pick",    tagColor: "#D4A017", dietary: ["vegetarian"],              allergens: "Gluten, Milk, Eggs" },
  // ── Mains ────────────────────────────────────────────────────────────────────
  { id: 19, category: "mains",     name: "Croque Monsieur",       price: "420 ETB", description: "Classic French grilled sandwich with premium ham, Gruyère cheese and béchamel sauce",             image: "https://images.unsplash.com/photo-1528736235302-52922df5c122?w=400&q=80", tag: null,             tagColor: null,      dietary: [],                          allergens: "Gluten, Milk, Eggs" },
  { id: 20, category: "mains",     name: "Quiche Lorraine",       price: "390 ETB", description: "Traditional French quiche with smoked bacon, caramelized onions and Gruyère in a buttery pastry shell", image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&q=80", tag: "Chef's Pick", tagColor: "#D4A017", dietary: [],                          allergens: "Gluten, Milk, Eggs" },
  { id: 21, category: "mains",     name: "Pasta Primavera",       price: "450 ETB", description: "Fresh tagliatelle with seasonal vegetables, cherry tomatoes and basil pesto",                     image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=400&q=80", tag: null,             tagColor: null,      dietary: ["vegetarian"],              allergens: "Gluten" },
  { id: 22, category: "mains",     name: "Niçoise Salad",         price: "380 ETB", description: "Classic French salad with seared tuna, olives, green beans, eggs and anchovy dressing",           image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80", tag: null,             tagColor: null,      dietary: ["gluten-free"],             allergens: "Fish, Eggs" },
  // ── Desserts ─────────────────────────────────────────────────────────────────
  { id: 23, category: "desserts",  name: "Tarte aux Fraises",     price: "280 ETB", description: "Classic French strawberry tart with vanilla custard cream and fresh seasonal berries",             image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80", tag: "New",            tagColor: "#D46A7E", dietary: ["vegetarian"],              allergens: "Gluten, Milk, Eggs" },
  { id: 24, category: "desserts",  name: "Crème Brûlée",          price: "320 ETB", description: "Classic French vanilla custard with a perfectly caramelized sugar crust",                         image: "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=400&q=80", tag: "Bestseller",     tagColor: "#D46A7E", dietary: ["vegetarian", "gluten-free"], allergens: "Milk, Eggs" },
  { id: 25, category: "desserts",  name: "Chocolate Fondant",     price: "350 ETB", description: "Warm dark chocolate lava cake with vanilla ice cream and gold leaf garnish",                       image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&q=80", tag: null,             tagColor: null,      dietary: ["vegetarian"],              allergens: "Gluten, Milk, Eggs" },
  { id: 26, category: "desserts",  name: "Macaron Selection",     price: "240 ETB", description: "Six house-made French macarons in seasonal flavors — rose, pistachio, salted caramel, and more",  image: "https://images.unsplash.com/photo-1558326567-98ae2405596b?w=400&q=80", tag: "Signature",      tagColor: "#D46A7E", dietary: ["vegetarian", "gluten-free"], allergens: "Milk, Eggs, Nuts" },
  // ── Signature Drinks ─────────────────────────────────────────────────────────
  { id: 27, category: "drinks",    name: "Rose Lemonade",         price: "220 ETB", description: "Fresh-squeezed lemonade infused with rose syrup and edible rose petals",                          image: "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=400&q=80", tag: "Signature",      tagColor: "#D46A7E", dietary: ["vegan", "gluten-free"],    allergens: "None" },
  { id: 28, category: "drinks",    name: "Mango Passion Cooler",  price: "240 ETB", description: "Fresh Ethiopian mango blended with passion fruit, mint and sparkling water",                       image: "https://images.unsplash.com/photo-1546173159-315724a31696?w=400&q=80", tag: null,             tagColor: null,      dietary: ["vegan", "gluten-free"],    allergens: "None" },
  { id: 29, category: "drinks",    name: "Lavender Latte",        price: "300 ETB", description: "House-made lavender syrup with oat milk and a double shot of espresso",                           image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&q=80", tag: "New",            tagColor: "#D4A017", dietary: ["vegan"],                   allergens: "None" },
  { id: 30, category: "drinks",    name: "Hibiscus Spritz",       price: "200 ETB", description: "Ethiopian hibiscus flower tea, sparkling water, fresh mint and a touch of honey",                 image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80", tag: null,             tagColor: null,      dietary: ["vegan", "gluten-free"],    allergens: "None" },
];

export const dietaryConfig: Record<DietaryTag, { label: string; color: string; bg: string }> = {
  vegan:        { label: "Vegan",        color: "#2D7A3A", bg: "rgba(45,122,58,0.12)"  },
  vegetarian:   { label: "Vegetarian",   color: "#5A8A2A", bg: "rgba(90,138,42,0.12)"  },
  "gluten-free":{ label: "Gluten-Free",  color: "#B8860B", bg: "rgba(184,134,11,0.12)" },
  "dairy-free": { label: "Dairy-Free",   color: "#1A7A8A", bg: "rgba(26,122,138,0.12)" },
  signature:    { label: "Signature",    color: "#D46A7E", bg: "rgba(212,106,126,0.12)"},
};
